### ISSUE TITLE
Remove go-ethereum dependencies

### ISSUE THREAD

**Issue by ferranbt** [umbracle/minimal#55]
These are the last go-ethereum dependencies to be removed:
- [x] Bn256 #123 
- [x] Ethash #100 
- [x] Rlp #122 
- [x] Types #119 
- [x] Crypto & Ecies #107

**Comment by lrettig** [comment]
It would be helpful to be able to see the merged PRs where the previous dependencies were removed.

**Comment by ferranbt** [comment]
Done! Thank you for the advice.
